### PR TITLE
Fix PTSD Position & update docs

### LINKED ISSUE #203: PTSD Position incorrectly implemented with inverted Y-axis
PTSD Position (from #175) incorrectly implemented with inverted Y-axis, causing mismatch with `Transform::translation` (world position)

https://github.com/ntut-open-source-club/practical-tools-for-simple-design/blob/d76c488000cfbc571f007c4d04f2849507101110/src/Util/Position.cpp#L9-L15

original (correct) convert:

https://github.com/ntut-open-source-club/practical-tools-for-simple-design/blob/0399023f675cb7a59ed0f26ea7bacdea66ef0fae/src/Util/Input.cpp#L79-L86

### PR DESCRIPTION
**Pull request by ntut-rick**
- Fix #203

### CODE REVIEW

**Review by NOOBDY — APPROVED** [review]
LMAO

File: include/Util/Position.hpp [hunk 1]
```diff
@@ -7,6 +7,15 @@ namespace Util {
 
 struct PTSDPosition;
 
+/**
+ * @class SDLPosition
```
Comment (Dragonfly911117) [inline include/Util/Position.hpp:11]: Consistently using either one of  `@struct` or `@class` here and line 33 would be better.

**Review by Dragonfly911117 — CHANGES_REQUESTED** [review]
Others seems fine to me

**Review by Dragonfly911117 — APPROVED** [review]
