### PR TITLE
Fix Delta time & Delay

### LINKED ISSUE #167: Argument for `SDL_Delay()` underflows in context.hpp
### Problem

Argument for `SDL_Delay()` in `Context::Update()` underflows when the `FPS_CAP` is low enough to make `frameTime - Util::Time::GetDeltaTime() < 0` 

### Steps to reproduce

- Have a low `FPS_CAP` in `config.hpp`
- Have a high delta time

### Expected behavior

Not to delay for a very long time like 4294967295 ms.

### PTSD version

c3642c5171939378e07762bef79841c79dc665c7

### Operating system/version

Windows 11 Pro

### CMake version

3.27.8

### CMakeCache.txt

[CMakeCache.txt](https://github.com/ntut-open-source-club/practical-tools-for-simple-design/files/14848809/CMakeCache.txt)

### OpenGL Info

```txt
[info] OpenGL Info
 [info]   Vendor: NVIDIA Corporation
 [info]   Renderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
 [info]   Version: 4.1.0 NVIDIA 551.23
 [info]   GLSL Version: 4.10 NVIDIA via Cg compiler
```

### PR DESCRIPTION
**Pull request by ntut-rick**
### About delta time issue
```
--|--Delay--|--UT--|--Delay--|--UT--|--
  |---Delta time---|            ^ Last delta time used here
  ^                ^
  (s_Last)         (s_Now) Time::Update here
```
#### After this PR (this diagram is recorded next to the implement)
```
--|--Delay--|--UT--|--Delay--|--UT--|--
            |---Delta time---|  ^ Last delta time used here
            ^                ^
            (s_Last)         (s_Now) Time::Update here
```
### Minor Changes

- Add `Util::Time`-related types `second_t`(`double`) & `ms_t`(`double`)
- `GetElapsedTimeMs()` used to return `unsigned long`, but now it returns `ms_t`
p.s. I'm not sure why it was designed this way.
- Variables (in `Util:Time`) related to SDL used to be `unsigned long`, but now they are `Uint64`, consistent with the SDL function declaration

#### Related issues
- Fix #167

### CODE REVIEW

**Review by NOOBDY — DISMISSED** [review]

**Review by NOOBDY — APPROVED** [review]

File: src/Core/Context.cpp [hunk 1]
```diff
@@ -118,14 +120,36 @@ void Context::Setup() {
...
+    // # Updating/rendering time is denoted as "UT"
+    Util::Time::Update();
+
+#ifdef DEBUG_DELTA_TIME
+    auto deltaTime = Util::Time::GetDeltaTimeMs();
+    LOG_DEBUG("Delta(Update+Delay): {:.1f}({:.1f}+{:.1f}) ms, FPS: {:.1f}",
+              deltaTime, updateTime,
+              updateTime < frameTime ? frameTime - updateTime : 0,
+              1000.0f / deltaTime);
+#endif // DEBUG_DELTA_TIME
```
Comment (NOOBDY) [inline src/Core/Context.cpp:152]: is this still needed?

File: src/Core/Context.cpp [hunk 2]
```diff
@@ -118,14 +120,36 @@ void Context::Setup() {
...
-    Util::Time::Update();
     Util::Input::Update();
     SDL_GL_SwapWindow(m_Window);
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
 
-    constexpr double frameTime =
-        FPS_CAP != 0 ? 1000 / static_cast<double>(FPS_CAP) : 0;
-    SDL_Delay(static_cast<Uint32>(frameTime - Util::Time::GetDeltaTime()));
+    constexpr ms_t frameTime =
+        FPS_CAP != 0 ? static_cast<float>(1000.0F / FPS_CAP) : 0;
```
Comment (ntut-rick) [inline src/Core/Context.cpp:128]: sorry my admired sonarcloud Prayge
```suggestion
        FPS_CAP != 0 ? 1000.0F / FPS_CAP : 0;
```

**Review by NOOBDY — APPROVED** [review]
